FROM jenkins/jenkins:lts

USER root

# Install required tools: Docker, AWS CLI, Terraform
RUN apt-get update && \
    apt-get install -y \
        docker.io \
        awscli \
        unzip \
        curl \
        gnupg \
        software-properties-common \
        lsb-release \
        apt-transport-https && \
    mkdir -p /var/lib/apt/lists/partial && chmod -R 755 /var/lib/apt/lists && \
    # Add HashiCorp repo for Terraform
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && \
    apt-get install -y terraform && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
