FROM jenkins/agent:latest
USER root

RUN apt-get update && \
    apt-get install -y docker.io awscli unzip curl gnupg software-properties-common lsb-release apt-transport-https && \
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && \
    apt-get install -y terraform && \
    groupadd -g 999 docker || true && usermod -aG docker jenkins

USER jenkins
